### ISSUE TITLE
Feature request: get objects from file(s)

### ISSUE THREAD

**Issue by ghost** [matteoparlato/Project-Kittan#17]
Add an "objects finder" section, which outputs strings of object filters.

Extra mile: let the user choose what objects they want to look for (tables, codeunits, reports, pages, ... and any combination)

For example: I want to look for all tables in a file or folder. The output could be: 36|37|110|111|112|113|114|115|5107|5108|6660|6661

Warning: there's a 2048 character limit for filters in the classic client (at least from NAV 2013 and up), so maybe split the string and warn the user if the filter exceeds that length.

**Comment by matteoparlato** [comment]
Feature added with #19
